#!/bin/bash
current_branch="$(git rev-parse --abbrev-ref HEAD)"
SKIP_BRANCHES="master|main|${current_branch}|${SKIP_BRANCHES:-"develop|development"}"

branches=()
while IFS='' read -r line
do
    branches+=("$line")
done < <(git --no-pager branch --no-color --format='%(refname:short)' | grep -v -x -E "$SKIP_BRANCHES")

trash=()

handle_choice () {
    echo -n "$branch [y/n/?]: "
    read -r -n 1 ans
    if [[ "$ans" == "y" ]]; then
        trash+=("$branch")
    fi
    if [[ "$ans" == "?" ]]; then
        git branch -vv --list "$branch"
        handle_choice
    fi
}

for branch in "${branches[@]}"; do
    handle_choice
    echo
done

if [ "${#trash[@]}" -lt "1" ]; then
    echo -e "\nnothing to delete"
    exit
fi

echo -e "\nyou will delete the following local branches:"
printf '%s\n' "${trash[@]}"
echo; echo -n "type 'trash' to do it: "
read -r ans

if [[ "$ans" == "trash" ]]; then
  for trashbranch in "${trash[@]}"; do
    git branch -D "$trashbranch"
  done
  echo 'done'
else
  echo 'coward'
fi
